demo/AngryBots/Release/UnityLoader.js
demo/AngryBots/index.html
demo/index.html

Demo polish

---

css/custom.css

add pre/code styling

---

demo/AngryBots/Release/AngryBots.js

Reverts WebAssembly/webassembly.github.io#14

Revert "Candidate for 0xc AngryBots"

---

community/feedback.md
docs/community/events/index.html
docs/community/feedback/index.html
docs/design/BinaryEncoding.md
docs/design/Events.md
docs/design/JS.md
docs/design/Modules.md
docs/design/Semantics.md
docs/design/TextFormat.md
docs/docs/binary-encoding/index.html
docs/docs/js/index.html
docs/docs/modules/index.html
docs/docs/semantics/index.html
docs/docs/text-format/index.html
docs/getting-started/js-api/index.html

- typo on JS API page
- new V8 bug link
- update to HEAD of design repo

Update site with small fixes & recent design repo commits

---

docs/design/BinaryEncoding.md
docs/design/Semantics.md
docs/docs/binary-encoding/index.html
docs/docs/semantics/index.html

This reflects the minimal upstream changes regarding the MVP v1 release of Wasm on the website as well

Update design documentation and regenerate HTML to reflect changes

---

getting-started/developers-guide.md

Add tip for args `--vs2017` if user build with Visual Studio 2017.

Update developers-guide.md for vs2017 build

---

css/custom.css
docs/css/custom.css

Added effect by using `transition: .5s ease;` in `.side-nav-item` classes found in:
- css/custom.css
- docs/css/custom.css

[ENHANCEMENT] Transition effect on .side-nav-item classes

---

getting-started/developers-guide.md

Just a more cleaner commands set for the "hello world" example.

Simple update for "hello world" commands

---

.travis.yml

This is a blind try at fixing Travis, based on their [docs](https://docs.travis-ci.com/user/languages/ruby/#bundler-20). Let's see if CI passes with this change...

Attempt at fixing CI

---

docs/getting-started/advanced-tools/index.html
getting-started/advanced-tools.md

wabt [renamed](https://github.com/WebAssembly/wabt/pull/617)
"wast2wasm" and "wasm2wast" to "wat2wasm" and "wasm2wat"; update the
website accordingly.

Change "wast2wasm" to "wat2wasm".

---

docs/getting-started/developers-guide/index.html
getting-started/developers-guide.md

*👋🏻 As some of you know, I've recently taken over work of updating the website to include more relevant content for new developers in this new age. This is the first in a series of small PRs towards that goal.*
Instead of duplicating an Emscripten tutorial, provide a curated list of links to tutorials or documentation that helps people get started with WebAssembly from various languages and environments.
This is an initial list and can and will be expanded over time.

Update Getting Started page

---

css/custom.css
docs/css/custom.css

I noticed that the hover effect on the side nav animates layout, which causes layout and paint on every frame. Here’s a quick fix to move that animation to the compositor.

Avoid repaints

---

docs/index.html
index.md

We'll probably want to redesign / reword this page further, but for now this should suffice as a more generic alternative to #130.

Remove specific langs from lead

---

features.json

per https://github.com/WebAssembly/meetings/blob/master/main/2020/CG-06-23.md meeting

Move bulk memory and and reftypes to phase 4

---

features.json

Firefox links
BigInt https://bugzilla.mozilla.org/show_bug.cgi?id=1631702#c1
bulkmem https://bugzilla.mozilla.org/show_bug.cgi?id=1528294#c0
multi-value https://bugzilla.mozilla.org/show_bug.cgi?id=1628321#c4
simd https://bugzilla.mozilla.org/show_bug.cgi?id=1625130
Chrome links
BigInt https://bugs.chromium.org/p/v8/issues/detail?id=7741#c21

Update Firefox and Chrome features support data

---

features.json

@RReverser, please take a look, thanks!

Update features.json for Firefox 79

---

features.json

We just published a new version of Wasmer supporting multivalue and bulk memory proposals 😊

Update Wasm supported features in Wasmer

---

features.json

https://github.com/WebAssembly/meetings/blob/master/main/2021/CG-02-16.md

Move SIMD to phase 4

---

features.json

Exception Handling behind #enable-experimental-webassembly-features flag

Update features.json for Chrome 90

---

features.json

Node.js 16.4 ships with V8 9.1
https://github.com/v8/v8/blob/master/src/wasm/wasm-feature-flags.h

Update wasm features support in Node.js

---

features.json

It's phase 3 and implemented in wasmtime at least.

Add entry for multi-memory proposal

---

features.json

Post from WebKit blog: https://webkit.org/blog/12140/new-webkit-features-in-safari-15-2/
Bug on WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=229681

Update Safari version to 15.2

---

features.json

(https://github.com/WebAssembly/wabt/pull/2086)

features.json: wasm2c adds memory64

---

features.json

Ref: https://github.com/WebAssembly/proposals/pull/156

move Type Reflection proposal to Phase 3

---

features.json

Reverts WebAssembly/website#313

Revert "Update Wasmtime's available features and how they are accessed"

---

features.json
roadmap.js

See also: https://github.com/GoogleChromeLabs/wasm-feature-detect/issues/60

features: add Wasm-GC and Chrome's current support

---

features.json

https://github.com/WebKit/WebKit/commit/3eb123c1f36f03ab8b1f521de8f01aaf541854c8
release notes: https://webkit.org/blog/13902/release-notes-for-safari-technology-preview-164/

Tail Calls were disabled in Safari TP 164

---

features.json

https://chromestatus.com/feature/5131077456232448

Mark extended-const as shipping in Chrome

---

features.json

Support for the tail-call proposal landed in https://github.com/bytecodealliance/wasmtime/pull/6774

Update features.json with Wasmtime tail-call support

---

features.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1571998

Tail calls are in Firefox Nightly

---

features.json

See https://bugs.chromium.org/p/v8/issues/detail?id=13918
and https://bugzilla.mozilla.org/show_bug.cgi?id=1782585

[Roadmap] Mark multi-memory as implemented in Chrome and Firefox

---

features.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1825077 and https://bugzilla.mozilla.org/show_bug.cgi?id=1774825

[Roadmap] Firefox implements GC behind a flag

---

community/resources.md

The existing subreddit is closed, and a new one has been created. Also, move Discord to the top of the list, as it's the most active community resource.
Fixes #341

Update subreddit link

---

features.json

See
https://bugzilla.mozilla.org/show_bug.cgi?id=1845373
and
https://groups.google.com/a/chromium.org/g/blink-dev/c/K_GpDF0y5Q8/m/XIJSfbTHBwAJ

Update GC stage and shipping

---

features.json

See https://chromestatus.com/feature/5106389887746048

Update Chrome release status for multi-memory

---

features.json

It's in Firefox Beta 121: https://www.mozilla.org/en-US/firefox/121.0beta/releasenotes/
https://bugzilla.mozilla.org/show_bug.cgi?id=1846789

Update Firefox support for tail calls in features.json

---

features.json

Update Node status for multi-memory

---

features.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1860816

Update Firefox shipping status for multi-memory

---

features.json

And document the Wasmtime support.
@tlively PTAL

Add the custom-page-sizes proposal to `features.json`

---

getting-started/developers-guide.md

Add python runtimes

---

features.json

Reference https://github.com/mdn/browser-compat-data/pull/17947

Update Safari CSP support

---

features.json

It's a phase 2 proposal that already has an implementation.

Add the `Wide Arithmetic` Proposal

---

getting-started/developers-guide.md

C# Link is wrong

---

css/custom.css
features.js

Allow feature table to expand outside content area

---

features.json

Merged in https://github.com/WebAssembly/wabt/pull/2508
(fyi @fitzgen)

features.json: add wasm2c support of custom-page-sizes

---

news/2025-03-20-wasm-2.0/index.md

I thought I kick off the news section with a post about Wasm 2.0. I'll follow up with a post about 3.0.
@dschuff, @sideshowbarker, can you please have a look at the first two paragraphs, to make sure that I don't say anything factually wrong or politically delicate wrt the W3C process?

Add news about Wasm 2.0

---

features.json

The CG voted in today's meeting to advance the proposal to phase 3.

Advance the custom-page-sizes proposal to phase 3

---

getting-started/developers-guide.md

This pull request adds an entry for Ruby to the list of supported languages for WebAssembly :)

Add Ruby link to developers-guide.md

---

getting-started/developers-guide.md

Updated page with a link to webR.

Added R to developers-guide.md

---

features.json

https://github.com/WebAssembly/proposals/pull/207/

JSPI is stage 4

---

features.json

Note: I need someone to create the actual fork for me.

Add more-array-constructors proposal to features.json

---

features.json

Update Chrome BranchHinting feature, shipped in v137

---

features.json
js/wasm-compat.js

@rossberg, regarding your comment in https://github.com/WebAssembly/website/pull/477#issuecomment-3311850143, please take a look at the changed status:

Change profiles status
