WebAssembly/website

- demo/AngryBots/index.html
This PR adds a (currently candidate) .wasm binary that matches the 0xb branch binary encoding in [design](https://github.com/WebAssembly/design).  The only thing missing (which I'll upload tomorrow assuming [design/#664](https://github.com/WebAssembly/design/pull/664) is merged) is the `br_table` value.  I confirmed locally that it runs in the three configurations: no wasm (which just has the message), FF nightly (0xa), FF with [patches](https://bugzilla.mozilla.org/show_bug.cgi?id=1263202) (0xb).
Happy to get any feedback and update the PR with new binary bits if any issues are found.  I'll of course wait to confirm this decodes in at least one other engine before merging.  (cc @binji @kripken @sunfishcode )
> Add 0xb demo bits

- css/custom.css
Minor CSS change to apply a default margin-left for ul tags on both html pages instead of just the demo.
Before:
After:
> Add default <ul> margin-left

- index.html
it takes you to kiwi IRC web client to make it easy for non IRC users to connect and interact.
> make IRC link clickable

- stepbystep/index.html
It's better to not recommend the wasm backend yet, as it isn't stable. It is also more steps to set up.
By default `emcc` uses `asm2wasm` which is stable.
> Recommend the current stable compiler path

- demo/AngryBots/Release/AngryBots.js
Update to the remaining anticipated 0xc features.
Additional Changes:
- Block signatures.
- Section opcodes.
- Minimally update Release/AngryBots.js to work with the new JS API.
- Include a binary-encoded wasm file in 0xc format.
I made up a syntax for block signatures in the flat text format, taking
care to allow for adding arguments and multiple results in the future.
For example:
``` 
block $label28 () : (i32)
``` 
Is a `block` no arguments and one return type which is i32.
However, I'm not attached to this particular syntax, and it can easily
be converted to something else if desired.
> Candidate for 0xc AngryBots

- demo/AngryBots/Release/AngryBots.js
- demo/AngryBots/index.html
- demo/index.md
This PR updates the demo to match SM's impl of the 0xD changes on `binary_0xd` branch in the design repo.  It also removes dependence on the `Wasm` object, using `WebAssembly.validate` to detect 0xc vs. 0xd, as discussed in #27.
Feedback welcome of whether this binary can be successfully decoded by other 0xD impls.
> Update demo to 0xD and remove use of Wasm object

- demo/AngryBots/Release/AngryBots.js
- demo/AngryBots/Release/UnityLoader.js
- demo/AngryBots/index.html
This PR feature-tests and uses `WebAssembly.compile`, if present, so that the demo can take advantage of parallel compilation.  It also adds some comments for anyone reading the code to understand what bits are temporary hacks.
> use WebAssembly.compile in demo, if present

- getting-started/js-api.md
Fix broken link in getting-started/js-api
was: 
/getting-started/advanced-tools/wabt-the-webassembly-binary-toolkit
should be:
/getting-started/advanced-tools/#wabt-the-webassembly-binary-toolkit
> getting-started: fix typo in link to advanced tools—wabt

- getting-started/js-api.md
That helps to avoid confusion and compile errors when the sample code is copied "as is" from the page.
> Change quites in the code examples

- docs/design/Events.md
I'm not sure whether the scope of this page is limited to talks given by people working on the standard. If it is not, this is a helpful talk that demonstrates using WASM with Node. The Node workflow is still clunky, but I think adventuresome developers might want to tinker with it, and this is the only demo of it I've seen.
> Add Node talk to community events page

- getting-started/developers-guide.md
Improve getting started instructions to refer to the appropriate steps for building latest Emscripten from source. Also use `emrun` instead of python web server, because `emrun` knows to provide proper HTTP response headers to the served files, which SimpleHTTPServer is not aware of. Add Windows instructions as well, and a section on prerequisites.
Once precompiled Emscripten packages are available which don't need building from source, the getting started docs can be rewritten to not require git, CMake or Visual Studio/gcc/Xcode.
> Update getting started developer's guide.

- getting-started/developers-guide.md
We have had precompiled toolchains distributed for a while now, so update Getting Started documentation to include a section on obtaining a precompiled toolchain.
> getting_started_with_precompiled_toolchain

- docs/getting-started/developers-guide/index.html
I believe the windows command to add emsdk to PATH is 'emsdk_env.bat' [link to section in documentation](https://github.com/juj/emsdk#installing-emsdk-directly-from-github)
> Changed to 'emsdk_env.bat' from 'emsdk_env'

- docs/getting-started/developers-guide/index.html
- getting-started/developers-guide.md
(Things do work in the meantime since github magically redirects everything.)
> Update links to emsdk repo, which has been transfered to emscripten-core/

- docs/design/TextFormat.md
- docs/docs/text-format/index.html
- docs/roadmap/index.html
- roadmap.md
LLVM has an official repository on Github now. Link to it instead of the mirror
repo.
> Link to official LLVM repo instead

- docs/design/TextFormat.md
- docs/docs/text-format/index.html
- docs/roadmap/index.html
- roadmap.md
In my attempt to link to the official LLVM repo, a mistake was made in
the new URL (I wrongly assumed the old mirror and the official mono-repo
has the same structure). This should fix that mistake.
> Fix Links to LLVM

- docs/getting-started/developers-guide/index.html
- getting-started/developers-guide.md
The emcc default is wasm anyhow.
CI errors on something unrelated about Ruby - any ideas?
```ruby
$ bundle install --jobs=3 --retry=3 --deployment
/home/travis/.rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```
> Remove emcc WASM=1 flag in developers' guide, as it has not been needed for a while

- docs/getting-started/developers-guide/index.html
- getting-started/developers-guide.md
The emsdk now has Windows binary builds, so no special process is needed there, and the old instructions for either using WSL or building from source are pretty onerous.
edit: background: WebAssembly/binaryen#2395
> Simplify instructions for downloading Emscripten

- .gitattributes
This should help with reviews by collapsing any changes in `docs` by default.
> Mark docs folder as autogenerated

- roadmap.md
This is the first usage of `phase` field.
Note that precise value doesn't matter (which decreases the pressure put on us in keeping those in sync), but "phase 4" vs "the rest" seems like a useful split for developers.
> Group features by status

- features.json
@lars-t-hansen [said](https://github.com/WebAssembly/website/pull/174#issuecomment-649455607) that bulkmem and multi-value will land in FF79, but I see those flags enabled by default in FF 78 stable 🤔
> Firefox 78 updates

- features.json
I've added [COOP+COEP](https://web.dev/coop-coep/) headers to the feature test page, which unlocks powerful APIs like shared memory. In particular, This flips "threads" on Firefox stable to true!
cc @chicoxyzzy just to double-check on someone else's Firefox :)
> Enable COOP+COEP on the feature test page

- features.json
Safari/JSC supports reference types behind the `JSC_useWebAssemblyReferences` runtime flag.
> Update Safari feature support

- features.json
Bulk memory and reference types have been fully supported since 0.19 and enabled by default since 0.20.
> Update supported features of Wasmtime

- features.json
This reverts commit ca3384d3a36f8b0c4407cfa242f06de9a929c527.
The release is now tagged and on the github releases page: https://github.com/bytecodealliance/wasmtime/releases/tag/v0.20.0
@RReverser, PTAL.
> Revert "Revert "Update supported features of Wasmtime (#193)""

- _includes/header.html
- _layouts/community.html
- community/contributing.md
- community/resources.md
- Add /resources page with some useful links for beginners.
- Update the old IRC link in "Contributing" to a #cg Discord chat instead.
- Hide outdated "Past events" page from the sidebar until we figure out how to sustainably maintain list of Wasm events.
> Update Community section

- features.json
- roadmap.md
After looking at the various unicode options, I think minus ➖ makes the most sense.
Fixes #171
Sorry I couldn't test this, when I try to build I get this:
```
Incremental build: disabled. Enable with --incremental
Generating... 
Liquid Exception: undefined method `includes_load_paths' for #<Jekyll::Site:0x000055c2eed09e70> in _layouts/getting-started.html
jekyll 3.1.6 | Error:  undefined method `includes_load_paths' for #<Jekyll::Site:0x000055c2eed09e70>
```
I can try again from my work machine tomorrow.
> Represent non-applicable roadmap features with 'N/A'. Fixes #171

- features.json
- roadmap.md
Can you take a look at this @RReverser? Thanks!
> Wasmtime 0.22

- features.json
It seems to be possible to enable it on stable too now.
@lars-t-hansen can you please confirm if it's still limited to x86 / x64?
> Update flag for Firefox SIMD

- features.json
Tail calls behind #enable-experimental-webassembly-features flag
> Update features.json for Chrome 89

- features.json
Mention origin trials as an alternative method to enable some WebAssembly features in Chrome
> Mention Origin Trials

- features.json
Safari 14.1 is available in macOS 11.3 Beta and iOS 14.5 Beta. Stable versions will probably be released in the end of March or early April.
> Update features.json with Safari 14.1 data

- getting-started/developers-guide.md
The AssemblyScript docs moved and broke the url
> Update AssemblyScript url

- features.json
Wasmer 2.0 (which will be released in 15 hours), fully supports the latest phase 4 WebAssembly proposals (SIMD and Reference Types)
> Update Wasmer features

- features.json
SIMD has shipped also on ARM64; exceptions and extended constant expressions are in the pipeline.
> Update Firefox features

- getting-started/developers-guide.md
The current link is not worked anymore, so I'm update it to the appropriate one. I hope this is right!
> Update tinygo getting started link

- features.json
Safari 15 just released with `Bulk memory operations`, `Reference types` and `Non-trapping float-to-int conversions` now being activated by default.
> Update Safari Feature Support for 15.0

- features.json
I had not been in the loop about the status of the memory64 proposal; I was pointed to https://webassembly.org/roadmap and, not seeing it there, thought it would be helpful to add a row for it.
> Add memory64 row to feature table

- features.json
https://blog.chromium.org/2021/10/chrome-96-beta-conditional-focus.html
> Update Chrome to version 96

- features.json
We've enabled a bunch of things in FF98 Nightly, and in any case the current FF version is 96.
> Update to Firefox 96

- features.json
Firefox 100 adds support for exception-handling [1]. This commit also updates the proposal phase to reflect its current status.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1759217
> Update features.json for Firefox 100

- css/custom.css
After the recent refactor (#283), the roadmap table shows a vertical scrollbar in some situations. This PR (allowing the table margin to be inherited) seems to fix the problem and doesn't seem to cause problems in Chrome or elsewhere.
E.g., here's Firefox on Ubuntu/X11 at the default 100% zoom level before this change: ![image](https://user-images.githubusercontent.com/208955/193962587-ce9e2abc-4162-4e42-953a-0abe70853ca6.png)
@andylizi
> CSS: prevent vertical scrolling of feature table on some Firefox configurations

- css/custom.css
- features.json
I've collected a bunch of version data for the feature table.
|  Feature | Version | Source |
| --- | --- | --- |
| multi-value | 0.17 | https://github.com/bytecodealliance/wasmtime/pull/1667 |
| bulk-memory | 0.20 | https://github.com/WebAssembly/website/pull/193 |
| reference-types | 0.20 | https://github.com/WebAssembly/website/pull/193 |
| simd | 0.33 | https://github.com/bytecodealliance/wasmtime/pull/3601 |
|  Feature | Version | Source |
| --- | --- | --- |
| mutable-globals | 0.7 | https://github.com/wasmerio/wasmer/pull/623 |
| bulk-memory | 1.0 | https://github.com/wasmerio/wasmer/commit/b3fbf79ecf60ae4368b27da7e14f492d30360dc3 |
| multi-value | 1.0 | https://github.com/wasmerio/wasmer/commit/bd2b648ca14764a1258167ed78465c5eb087617a |
| reference-types | 2.0 | …
> Add more data to the feature table

- features.json
Type reflection is available in Chrome and Node.js behind a flag.
> Update Chrome's support of type reflection, v2

- .github/workflows/deploy.yml
Auto-deployment stopped working after renaming `master` branch to `main`.
> Fix Github workflow branch name

- features.json
Wasmtime now has support for the threads proposal; this change adds that. It also uses the correct `--wasm-features` flag for enabling optional features.
> Update Wasmtime's available features and how they are accessed

- .github/workflows/ci.yml
- features.json
- features.schema.json
- roadmap.js
To avoid situations like https://github.com/WebAssembly/website/pull/301#discussion_r1068352138 happening again.
> Validate `features.json` during CI

- features.json
This was a part of the reverted #313; this provides the correct flag syntax for several off-by-default features.
> Update Wasmtime flags

- features.json
Added information for the version of Deno (1.1.2) which first enabled support for the experimental "JS BigInt to Wasm i64 integration" proposal.
This is according to https://github.com/denoland/deno/releases?page=13.
> Added Deno minimum version for bigint proposal

- features.json
The [Module Linking](https://github.com/WebAssembly/module-linking#readme) proposal is [suspended](https://github.com/WebAssembly/proposals/blob/main/inactive-proposals.md) in favor of the Component Model and currently inactive. It seems a bit out of place to keep it on the roadmap, which doesn't even include active phase 1 proposals.
> features: remove Module Linking

- features.json
Node first supported bigint integration in version 16.0, or in version 14.x and 15.x with `--experimental-wasm-bigint`.
> Add minimum version for node bigint integration

- features.json
Wasmer has supported typeReflection in both the sys and js targets since 2.0 (in the sys feature since 1.0).
This PR reflects that on the feature set for Wasmer.
> Note: we support it in js thanks to a polyfill made with wasmparser, hopefully that will go away once TypeReflection is properly supported by most of browsers.
Thanks!
> Added typeReflection feature in Wasmer

- features.json
Tail call is on by default in Chrome 112.
Relaxed SIMD and memory64 have been "staged", meaning they are enabled under the experimental wasm features flag, (rather than their own flags).
> Update Chrome status for tail call, relaxed SIMD, and memory64

- features.json
extended-const has been staged (https://bugs.chromium.org/p/chromium/issues/detail?id=1416400#c4) meaning it's now available behind the general "experimental webassembly features" flag.
> Update Chrome flag for extended-const proposal

- features.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1814421
> Mark extended-const as shipped in Firefox 112

- features.json
Note: the feature detection library release doesn't have jspi yet, so we'll have to update that later.
> Add JSPI to the roadmap.

- features.json
Chrome, wasmtime and wasmer were a little outdated / inaccurate.
> Update some features

- features.json
Excerpt from node --v8-options:
--experimental-wasm-gc (enable prototype garbage collection for wasm)
type: bool  default: --noexperimental-wasm-gc
From what I can tell the flag is available since at least node 16
> [Roadmap] Nodejs implements GC behind a flag

- features.json
wasm2c added support for tail calls behind a flag in version 1.0.34 (https://github.com/WebAssembly/wabt/releases/tag/1.0.34).
> Update wasm2c status for tail calls

- roadmap.js
- roadmap.md
Use https://unpkg.com/wasm-feature-detect@latest/dist/esm/index.js so we always include the latest build dynamically.
> Switch to evergreen URL for wasm-feature-detect library

- features.json
https://github.com/bytecodealliance/wasmtime/releases/tag/v15.0.0
> The WebAssembly threads, multi-memory, and relaxed-simd proposals are now enabled by default.
> https://github.com/bytecodealliance/wasmtime/pull/7285
I wasn't sure whether to specify the version as "15" or "15.0" (or even "15.0.0"). It seems to be inconsistent in the table. I used 15, as wasmtime's releases are similar to a browser where on a fixed schedule they bump the major version and bugfixes are done as patch versions (minor versions aren't used).
> Update features for wasmtime 15

- _includes/header.html
- community/feedback.md
- features.js
- features.md
When this page was created along with the wasm MVP, all the listed features were in the future, so it served as a roadmap for what was to come. Now it includes all the feature extensions that have been added since, and its primary usefulness is actually for developers to look up which engine versions implement which features (including past and near-future features which have implementations behind flags). So a better name than "roadmap" or "future features" would be something like "feature extensions". 
Also fixes #329
> Rename roadmap to "feature extensions"

- features.json
Safari shipped wasm-bigint separately from BigInt64Array.
> Add note for bigint feature

- features.json
Using [Binaryen v116](https://github.com/WebAssembly/binaryen/tree/version_116), assemble `pairs.wat`
```wat
(module
(type $pair (struct (field $fst f64) (field $snd f64)))
(func (export "cons") (param $a f64) (param $b f64) (result (ref $pair))
(struct.new $pair
(local.get $a)
(local.get $b)))
(func (export "sub") (param $ab (ref $pair)) (result f64)
(f64.sub
(struct.get $pair $fst
(local.get $ab))
(struct.get $pair $snd
(local.get $ab)))))
```
via this command:
```sh
wasm-as --enable-reference-types --enable-gc pairs.wat
```
Then download the Node nightlies from Jan 4 and Jan 5:
- https://nodejs.org/download/nightly/v22.0.0-nightly20240104084d761dfc/
- https://nodejs.org/download/nightly/v22.0.0-nightly2024010568c8472ed9/
And with each of those nightlies, try to run `pairs.js`
```js …
```
> Update Node status for GC

- features.json
Using [Binaryen v116](https://github.com/WebAssembly/binaryen/tree/version_116), assemble `fac.wat` (adapted from [here](https://github.com/WebAssembly/tail-call/blob/6f44ca27af411a0f6bc4e07520807d7adfc0de88/proposals/tail-call/Overview.md#examples))
```wat
(module
(func (export "fac") (param $x i64) (result i64)
(return_call $fac-aux (local.get $x) (i64.const 1)))
(func $fac-aux (param $x i64) (param $r i64) (result i64)
(if (i64.eqz (local.get $x))
(then (return (local.get $r)))
(else
(return_call $fac-aux
(i64.sub (local.get $x) (i64.const 1))
(i64.mul (local.get $x) (local.get $r)))))))
```
via this command:
```sh
wasm-as --enable-tail-call fac.wat
```
Then try to run `fac.mjs`
```js
import * as fs from "fs/promises";
const bytes = await fs.readFile("fac.wasm");
const mod = await …
```
> Update Node status for tail calls

- features.json
https://github.com/WebKit/WebKit/commit/fbf101220cf95a9973131d63f20b8e4507dff638 is tagged with "Safari-609.1.11.2" which https://github.com/mdn/browser-compat-data/blob/main/browsers/safari.json suggests corresponds to Safari 13.1
> Update Safari support for multi-value

- features.json
Enabled in STP 184: https://webkit.org/blog/14780/release-notes-for-safari-technology-preview-184/
> Add extended-const to Safari

- features.json
The `--wasm-features` flag has been replaced with `--wasm` in the new CLI for wasmtime 14.0 and later.
> Update wasmtime CLI options for enabling features

- features.json
Apparently the situation is a little bit complicated. The feature is enabled since [Version 21](https://github.com/bytecodealliance/wasmtime/blob/release-21.0.0/RELEASES.md#added), but only for the Cranelift backend, except for the s390x architecture.
However, the feature was accidentally not active until [Version 22](https://github.com/bytecodealliance/wasmtime/pull/8682).
Also wasmtime 22 isn't out yet (should come out June 17th).
> `tail-calls` for `wasmtime`

- features.json
This begins tracking JSPI support on Firefox, which has been merged as part of Firefox 127 (nightly). Implementation work is still ongoing, but a minimal version appears to be working already. I don't think it's stable yet, but I think it should be available for testing behind a flag?
@yurydelendik as the implementer of this in Firefox, can I ask you to review the diff here? Ty!
- [Firefox spec position (positive)](https://mozilla.github.io/standards-positions/#wasm-js-promise-integration)
- [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1897981)
> Begin tracking JSPI support for Firefox

- features.js
- features.json
- features.schema.json
After seeing https://labs.leaningtech.com/blog/branch-hinting yesterday, I was quite surprised to read that not only is this proposal done, but it's also implemented in all the browsers, and yet it's not even tracked in the `features.json` file.
So I took it upon myself to make sure that all features that are in at least phase 3 (implementation phase) are tracked and up to date. While doing this I however noticed that with the recent addition of "Custom Page Sizes", at least one phase 1 feature is also tracked now. So I exhaustively updated the `features.json` file to include all features that are implemented in at least one engine as well.
With there being a lot more proposals that are being tracked now, I thought it would also make sense to properly reflect the phases on the website, …
> Track and update all the implemented features

- features.json
> Wasmtime has implemented and enabled-by-default the extended-const proposal in version 25

- features.json
https://webkit.org/blog/15798/release-notes-for-safari-technology-preview-202/
> Note GC and tail call support in Safari TP 202

- features.json
This is following up on https://github.com/WebAssembly/website/pull/396.
The new GraalWasm landing page is now available at https://www.graalvm.org/webassembly/.
> Update link for GraalWasm.

- features.json
- This adds the `Stack Switching` Proposal to the list which reached phase 2 and has an in-progress implementation in V8.
- JS String Builtins are shipping in Chrome 130.
- Type Reflection is enabled by default in Firefox Nightly.
- Safari is shipping an in-progress implementation in Safari Technology Preview 202 (not mentioned in the changelog).
- Fixed some mistakes in Node.js.
- Wasmtime 24 supports the `Tail Call` Proposal on all targets.
> Add `Stack Switching` and Update Features

- features.json
Release notes https://webkit.org/blog/15999/release-notes-for-safari-technology-preview-205/
I've tested it `wasm-feature-detect` on https://webassembly.org/features/ as well
> Update Exception Handling with exnref in Safari TP

- getting-started/developers-guide.md
This PR adds a link to the Haskell-WASM documentation in the Developer Guide section of the WebAssembly website. The addition provides an important resource for developers who may be interested in learning more about using Haskell with WebAssembly.
@tomayac
> Add Haskell link to developers-guide.md

- _includes/header.html
Per some CG meeting discussion :)
(This PR is a bit cheeky, and it may be better to instead update the contents of the banner to reflect what is currently shipped.)
> Remove the Wasm 1.0 banner

- features.json
This additionally updates Wide Arithmetic to Phase 3. Also Deno now supports JS String Builtins.
> Compilation Hints are now in Phase 2

- features.json
`--experimental-wasm-stack-switching` is a deprecated flag for the JSPI proposal and not related to stack switching. Stack switching will be implemented behind `--experimental-wasmfx` but is still in a very early stage.
> Remove wasm stack switching flag mention for V8

- features.json
Exceptions are now supported as per:
https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#WebAssembly
> Updates for Safari 18.4

- _includes/header.html
- features.md
\#361 renamed this page from "Future features" to "Feature Extensions', as many of these features are standardized and widely implemented today. Looking at it now, the word "extensions" may also be misleading, as it may be read as suggesting that the MVP remains the base language, with all other features being held separate, as discrete extras.
In practice, when features are added to the spec, they are integrated and not kept separate. They appear as indistinguishable from the features that were in the MVP.
Consequently, I propose this page be titled "Feature Status", as it documents the implementation status of various features.
> Rename "Feature Extensions" to "Feature Status"

- features.json
Chrome shipped exnref and JSPI in v137.
> features.json: Update Chrome features

- features.json
Implemented via https://github.com/WebKit/WebKit/commit/3a60ed81db08242709d161f2dce472aa228f86c9 in Safari 13.1.
See also: https://github.com/mdn/browser-compat-data/pull/27201
> Update Safari version for mutable globals
